---
title: "{{< var titles.annotation.long >}}"
#author:
date: 2024-09-01
date-modified: last-modified

format:
  html: default
  pdf: default
format-links: [pdf]
---


## Критерии допуска к итоговой аттестации

Итоговая аттестация проходит в виде защиты проекта, подготовленного в рамках модуля
[Итоговый проект](/project/index.qmd "Итоговый проект").

К итоговой аттестации не допускаются слушатели, не достигшие в ходе итогового ассесмента от АНО ВО &laquo;Университет Иннополис&raquo; целевого уровня развития компетенций (уровень &laquo;Базовый&raquo;).


## Содержание итоговой аттестации (защиты проекта)
Итоговые аттестационные испытания включают следующие оценочные мероприятия:

1. устная презентация проекта;
2. ответы на вопросы членов аттестационной комиссии по проекту.


## Критерии оценки

### Критерии оценки устной презентации:
- самостоятельный проект с анализом проблемы, бизнес-процессов и рисков с самостоятельными выводами и примерами,
- четкое соблюдение структуры презентации,
- представление описания функциональных требований и/или технического задания с учетом требований &laquo;заказчика&raquo; и пользовательской оптимизации.

### Критерии оценки ответов на вопросы:
- логичность и правильность изложения содержания ответа на вопрос;
- достаточная аргументация;
- эффективное взаимодействие с членами экзаменационной комиссии.

### Критериями оценки представленной работы
Основными критериями оценки выполненной обучающимся и представленной для проверки работы являются:

1. Степень соответствия выполненного задания поставленным требованиям.
2. Структурирование и комментирование практической работы.
3. Уникальность выполнение работы (отличие от работ коллег).
4. Успешные ответы на контрольные вопросы.


## Результаты аттестации
- **&laquo;Отлично&raquo;** --- оформление и содержание соответствуют требованиям, критерии выдержаны, проект отвечает требованиям и учитывает риски, защита всего перечня контрольных вопросов.

- **&laquo;Хорошо&raquo;** --- оформление и содержание соответствуют требованиям, критерии выдержаны, проект отвечает не всем требованиям и учитывает часть рисков, защита только 80 % контрольных вопросов.

- **&laquo;Удовлетворительно&raquo;** --- оформление и содержание не полностью соответствуют требованиям, критерии выдержаны, проект отвечает не всем требованиям и не учитывает риски, защита только 61 % контрольных вопросов.

- **&laquo;Неудовлетворительно&raquo;** --- оформление и содержание не соответствуют требованиям; проект не отвечает требованиям и не учитывает риски; защита 60% и менее контрольных вопросов.
