---
title: Отчет по стажировке
#author:
date: 2024-09-01
date-modified: last-modified

format:
  html: default
  pdf: default
format-links: [pdf]
---

## Защита отчета

По итогу прохождения стажировки студентами формируется отчет команды о прохождении стажировки.

В ходе защиты отчета о стажировке студенты должны продемонстрировать:

1. Знание актуальных направлений развития  сферы Legaltech и понимание роли и значения для сферы  продуктов компании, в которой группа проходила стажировку.
2. Рассказать, а по возможности продемонстрировать приобретенные профессиональные практические навыки.
3. Продемонстрировать выполнения заданий, полученных в ходе стажировки.
4. Оценить вклад стажировки в работу над итоговым проектом.

В ходе защиты отчета руководитель стажировки оценивает логичность изложения отчёта, полноту описания содержания стажировки и итогов её прохождения, соответствие оформления требованиям (шрифт, поля, интервал, ссылки на использованные источники).

## Критерии оценки

По результатам защиты отчета выставляются отметки по двухбалльной шкале (&laquo;удовлетворительно&raquo; --- &laquo;зачтено&raquo;, &laquo;неудовлетворительно&raquo; --- &laquo;не зачтено&raquo;).
При определении оценки промежуточной аттестационной необходимо руководствоваться следующими критериями:

| Уровень усвоения | Критерии оценивания уровня усвоенных знаний, умений, приобретённых владений | Система оценивания |
| :--- | :--- | :--- |
| Минимальный уровень не достигнут | Слушатель ответил правильно на менее 60% предложенных вопросов. | не зачтено |
| Минимальный уровень достигнут | Слушатель ответил правильно на 60% вопросов и более. | зачтено |
