---
title: "{{< var titles.annotation.long >}}"
#author:
date: 2024-09-01
date-modified: last-modified
---


## Цель реализации программы дисциплины:
- получение обучающимися теоретических знаний о системном, процессно-ориентированном подходе к управлению деятельностью, методологиях и инструментах моделирования и анализа бизнес-процессов.


## Планируемые результаты обучения:
По итогам освоения дисциплины (модуля) обучающийся приобретает способности:

- читает и правильно интерпретирует ER-диаграммы (Сущность-Связь);
- распознаёт особенности функциональной, процессной и проектной модели управления в деятельности организации;
- использует терминологию процессного управления;
- определяет цели и метрики бизнес-процессов;
- строит eEPC-диаграммы для моделей бизнес-процессов;
- находит и исправляет ошибки в eEPC-диаграммах;
- сравнивает особенности 12-процессной модели, моделей eTOM, SCORe, моделей SAP, IBM;
- формулирует цели и методы анализа бизнес-процессов;
- анализирует причинно-следственные связи;
- идентифицирует и классифицирует ошибки бизнес-процессов, предлагает способы их исправления;
- самостоятельно выделяет бизнес-процессы по описанию деятельности организации;
- формулирует основные подходы концепции управления бизнес-процессами - Business Process Management (BPM);
- разрабатывает модели бизнес-процессов в виде BPMN-диаграмм;
- оценивает применимость подхода Process mining для анализа бизнес-процессов;
- владеет базовой терминологией, связанной с управлением рисками.


## Оценка качества освоения дисциплины
Оценка качества освоения программы по дисциплине &laquo;Анализ и моделирование бизнес-процессов организации&raquo; подразумевает три формы: текущий контроль, рубежный контроль и промежуточный контроль успеваемости.

**Текущий контроль** заключается в проверке домашних заданий, выполняемых слушателями к каждому практическому занятию. В рамках практических занятий по анализу бизнес-процессов планируется составление описания, представленного в виде блок-схем, одного юридического бизнес-процесса отдельно взятой компании.

**Рубежный контроль** проводится в течение семестра в форме письменного теста или электронного тестирования.

**Промежуточный контроль** успеваемости по дисциплине проводится на [зачете](credit.qmd) и [экзамене](exam.qmd).

Для успешной сдачи зачета и экзамена слушателю необходимо:

- пройти промежуточный и итоговый ассесмент (проверку) Университета &laquo;Иннополис&raquo;;
- выполнить задание по созданию алгоритма под конкретную задачу.
