---
title: Экзамен
#author:
date: 2024-09-01
date-modified: last-modified

format:
  html: default
---


## Вопросы для подготовки к экзамену

### Тема 1. {{< meta course.topic.1 >}}

1. Цели и задачи управления бизнес-процессами.
2. Определение бизнес-процесса.
3. Понятие кросс-функционального и «сквозного» бизнес-процесса.
4. Системный анализ и проектирование.
5. Принципы структурного подхода.
6. Средства структурного анализа и их взаимосвязь.
7. Процессно-ориентированное управление.
8. Виды бизнес – процессов организации.
9. Форматы описания бизнес-процессов: текстовый, табличный, графической.
10. Кросс-функциональные и «сквозные» бизнес-процессы.
11. Кросс-функциональные бизнес-процессы и их оптимизация.
12. «Сквозные» бизнес-процессы и совершенствование управления.
13. Принципы процессного подхода.
14. Ключевые элементы процессного подхода.
15. Три способа описания БП.
16. Организационные характеристики процессно-ориентированной организации.
17. Преимущества процессного подхода в управлении.
18. Повышение эффективности работы организаций на основе процессного подхода.

### Тема 2. {{< meta course.topic.2 >}}

19. Анализ бизнес-процессов как составная часть работ по их улучшению.
20. Показатели, определяемые в результате анализа бизнес-процессов.
21. Методы анализа бизнес-процессов.
22. Анализ времени выполнения бизнес-процессов.
23. Анализ «бутылочного горлышка» /узких мест.
24. Показатели анализа бизнес-процессов.
25. Применение технологии Process Мining для анализа.
23. Классификация ошибок процесса.
27. Анализ ошибок процесса.

### Тема 3. {{< meta course.topic.3 >}}

28. Основные подходы концепции управления бизнес-процессами (Business Process Management, BPM) как основы приведения процессов организации в соответствие с ее целями.
29. Ключевые концепции свода знаний BPM СВОК 3 по управлению процессами.
30. Уровни процессов компании согласно СВОК 3.0.
31. Горизонтальное взаимодействие функциональных подразделений.
32. Моделирование бизнес-процессов – один из методов улучшения качества и эффективности работы организации.
33. Стадии моделирования бизнес-процессов.
34. Нотации моделирования бизнес-процессов (BPMN, EPC, SIPOC и другие).
35. Моделирование бизнес-процессов в нотации BPMN
36. Средства моделирования бизнес-процессов
37. Виды моделирования бизнес-процессов организации.
38. Имитационное моделирование.
39. Основные принципы моделирования БП.
40. Методология структурного анализа и проектирования SADT.
41. Методология ARIS (Architecture of Integrated Information Systems).
42. Структурные модели унифицированного языка UML (Unified Model Language).
43. Назначение модели «сущность-связь» (ERM, Entity-Relationship Model или ER-модель) и нотации для ее визуализации.
44. Моделирование бизнес-процессов в нотации BPMN.
45. Нотации моделирования бизнес-процессов (BPMN, еEPC, SIPOC и другие).

### Тема 3. {{< meta course.topic.3 >}}

46. Подходы к управлению организацией для совершенствования бизнес-процессов.
47. Понятия «реинжиниринг бизнес-процессов» и «реструктуризация предприятия».
48. Этапы проведения совершенствования бизнес-процессов.
49. Цели и критерии оптимизации бизнес-процессов.
50. Методы и инструменты оптимизации бизнес-процессов.
51. Методы оптимизации БП: метод параллельного выполнения работ, метод пяти вопросов, метод устранения временных разрывов, метод вариативности БП и другие.
52. Методы оптимизации БП: вертикальное и горизонтальное сжатие.
53. Технология оптимизации бизнес-процессов.
54. Референтные модели бизнес-процессов eTOM, APQC PCF, BIAN, SCORE.
55. Модели IBM Industry Models.
56. Эталонная 13-процессная модель процессов. Назначение и структура.
57. Основные элементы технологий постоянного совершенствования бизнес-процессов.
58. Повышения эффективности бизнес-процессов при внедрении технологий нейросетей.
59. Основные технологии RPA (robotic process automation), применяемые для оптимизации бизнес-процессов.
60. Тренд автоматизации бизнес-процессов - системы ACM (adaptive case management).
61. Понятие систем Business Process Management Suite.
62. Примеры автоматизации бизнес-процессов с использованием BPMS систем.
63. Этапы управления рисками.
