---
title: "{{< var titles.annotation.long >}}"
#author:
date: 2024-09-01
date-modified: last-modified
format:
  html
---


## Цель выполнения итогового проекта:

- определить, насколько систематизированы, закреплены и расширены практические умения слушателя программы профессиональной переподготовки;
- показать умение самостоятельно разрабатывать конкретную проблему в области права, систематизировать и обобщать информацию на английском языке;
- свидетельствовать об умении излагать свои мысли, аргументировать выдвинутые гипотезы и предложения, правильно пользоваться профессиональной терминологией;
- углубить навыки исследовательской и аналитической работы.


## Этапы выполнения итогового проекта:

Процесс выполнения итогового проекта включает в себя следующие этапы:

1. Формирование команд. Назначение руководителя и выбор компании для подготовки проекта.
2. Подбор и изучение законодательных, нормативных и научных источников литературы по рассматриваемой проблеме.
3. Изучение проблемы с применением полученных знаний в ходе стажировки.
4. Подготовка проекта, включающего в себя описание функциональных требований.
5. Предоставление работы руководителю для проверки.
6. Окончательное редактирование работы с учетом замечаний руководителя.
7. Защита проекта в ходе итоговой аттестации.
