---
title: Требования к отчету по проекту
author:
  - Голкина Г.Е.
date: 2025-09-01
date-modified: last-modified

format:
  html: default
---


## Требования к содержанию

Отчет по проекту должен включать:

- титульный лист;
- аннотация на русском и иностранном языках (Приложение 4);
- содержание;
- введение;
- основную часть, состоящую пяти разделов;
- заключение, включающее выводы и предложения (рекомендации);
- список используемых источников;
- приложения (при необходимости).

Проект выполняется по актуальной для получаемого направления теме.
Актуальность темы и основные цели работы аргументируются во введении.
Отчет по проекту должен быть выполнен автором (авторами) самостоятельно со ссылками на используемую литературу и другие источники.

Результатом выполнения работы является достижение целей и задач, сформулированных во введении.
Содержание работы и уровень ее исполнения должны удовлетворять современным требованиям по присваиваемой квалификации.


## Требования к структуре

В структуре отчета выделяются:

- титульный лист;
- оглавление;
- введение;
- основная часть;
- заключение;
- список используемой литературы;
- приложения.

**Во введении** должны содержаться:

- **аргументация актуальности** темы проекта (например, автоматизация рутинного юридического процесса, внедрение новой технологии обработки юридической документации, автоматизация сквозного бизнес-процесса в юридической компании/подразделении и др.);

- **цель проекта** (цель должна быть сформулирована по SMART и связана с автоматизацией какого-либо юридического процесса (процессов). Проект может быть связан:
  -  с разработкой собственного продукта (программы, программного модуля, информационной системы) «с нуля», в том числе с использованием имеющихся на рынке low/no-code систем (например, разработка конструкторов, генераторов юридических документов, калькуляторов, чат-ботов с использованием конструкторов Botman.one/TurboContract и др.) и с интеграцией с существующими в организации информационными системами;
  - с внедрением в подразделении/компании существующего на рынке готового коробочного решения (информационной системы) без доработки;
  - с внедрением имеющегося на рынке готового IT-решения с доработкой и интеграцией с существующими в организации информационными системами.

- **задачи проекта**, т.е. шаги на пути достижения цели. При формулировании задач необходимо применять глаголы совершенного вида (например, подготовить, выполнить, обосновать, сформировать, построить, разработать и др.).
Например,
  - выполнить описание организации, являющейся объектом автоматизации, и ее организационной структуры;
  - выполнить анализ существующей организации бизнес и информационных процессов;
  - сформировать предложения по автоматизации (информатизации) бизнес-процессов с учетом анализа рынка программного обеспечения и IТ-технологий, выбора технологии проектирования ИС;
  - построить и обосновать модель новой организации бизнес-процессов;
  - разработать спецификацию функциональных требований к информационной системе;
  - выполнить календарно-ресурсное планирование проекта, определить риски и описать меры, предпринимаемые для противодействия рискам.

- **практическая значимость** проекта (например, полученные результаты могут быть использованы для автоматизации юридических процессов в аналогичных компаниях).

Объем введения не более 5 страниц.

В структуре основной части отчета должны быть выделены разделы (1,2,3,4,5), и в их составе –-- подразделы (1.1, 1.2, 1.3..., 2.1, 2.2 и т. п.).
Названия разделов и подразделов должны быть сформулированы, по возможности, кратко и отражать их содержание.
Названия подразделов не должны повторять названия разделов.


## Требования к объему

Требуемый объем отчета 30-50 страниц (минимум 30 страниц без приложений) машинописного текста, включая таблицы, графический и табличный материал. Приложения не входят в требуемый объем работы.
Объем приложения не ограничен.
Количество источников литературы --– не менее 20.

**Уникальность выпускной квалификационной работы должна быть не менее 65%.**


## Требования к оформлению

Работа выполняется на листах формата А4 (210х297 мм), пронумерованных и сброшюрованных.
Отчет по проекту печатается на листах бумаги стандартного формата А4 на одной стороне листа.

Все страницы отчета обязательно должны быть пронумерованы.
Нумерация листов --– сквозная, через всю работу.
Приложения должны иметь общую с остальной частью документа сквозную нумерацию страниц.
Для нумерации используются арабские цифры (1, 2, 3, …).
Порядковый номер страницы печатают на середине верхнего поля страницы.
Титульный лист и листы с оглавлением не нумеруются, но обязательно учитываются при подсчете количества страниц отчета.
Номера страниц должны быть видны, начиная с введения и заканчивая последним листом отчета.

Название каждого раздела/подраздела должно иметь более крупный шрифт, чем остальной текст или иметь полужирное начертание.
Заголовки разделов/подразделов отчета следует располагать в середине строки без точки в конце.
Если заголовки содержат несколько предложений, их разделяют точками.
В названии разделов допускается, чтобы все буквы были прописными.

Каждый раздел отчета (введение, разделы основной части, заключение) следует начинать с новой страницы. Название раздела отделяют от текста и от названия подраздела двойным между абзацным интервалом (18пт).

Каждый подраздел не должен начинаться с новой страницы, но продолжаться. Название подраздела также отделяют от текста сверху и снизу двойным между абзацными интервалами (18пт).

Все таблицы и рисунки должны быть последовательно пронумерованы. Нумерация сквозная. Для нумерации используются арабские цифры (1, 2, …).

Работа должна быть выполнена на ПК через 1,5 интервала шрифтом Times New Roman, размер шрифта – 14 пт.

Поля: верхнее и нижнее – 25 мм, левое – 30 мм, правое – 10 мм.
