---
title: Примерная структура отчета по проекту
author:
  - Голкина Г.Е.
date: 2024-09-01
date-modified: last-modified

format:
  html: default
---


## Введение
- Актуальность проекта.
- Объект и предмет автоматизации.
- Цель и задачи проекта.
- Практическая значимость проекта


## Раздел 1.
Описание организации, являющейся объектом автоматизации (Технико-экономическая характеристика объекта автоматизации)

### Подраздел 1.1.
Экономический анализ деятельности организации (миссия организации, система целей и ключевых показателей эффективности, стратегия развития и бизнес-архитектура предприятия).

### Подраздел 1.2.
Организационная структура и система управления.

### Подраздел 1.3.
Состояние ИТ в организации (степень автоматизации процессов, покрытие функциональных областей).

## Раздел 2.
Анализ существующей организации бизнес и информационных процессов

### Подраздел  2.1.
Описание существующей организации бизнес и информационных процессов (приветствуется построение модели бизнес-процесса «as-is» с использованием любой из нотаций IDEF0, BPMN, eEPC/EPC и др.).

### Подраздел 2.2.
Анализ недостатков (проблем, узких мест) существующей организации бизнес и информационных процессов.

### Подраздел 2.3.
Формирование предложений по автоматизации (информатизации) бизнес и информационных процессов.

Предложения формируются с учетом:

- анализа успешных IТ-проектов в рассматриваемой области;
- анализа рынка программного обеспечения и IТ-технологий.


## Раздел 3.
Постановка задачи автоматизации (информатизации) бизнес и информационных процессов (решения задач, комплекса задач, подсистем)

### Подраздел 3.1.
Цели и задачи проекта автоматизации (информатизации) бизнес и информационных процессов. Сущность разрабатываемого комплекса задач (программы, программного модуля, информационной системы).

### Подраздел 3.2.
Построение и обоснование модели новой организации бизнес и информационных процессов (построить модель бизнес-процесса «to-be» с использованием любой из нотаций IDEF0, BPMN, eEPC/EPC и др.).

### Подраздел 3.3.
Функциональные требования к информационной системе.
Составляются в виде таблицы, в которой для каждой автоматизируемой функции необходимо описать входные и выходные информационные потоки, участников и регламент выполнения).


## Раздел 4.
Календарно-ресурсное планирование проекта, анализ рисков

### Подраздел 4.1.
Обоснование выбора модели жизненного цикла и подхода к разработке ИС/ПО:

- модели ЖЦ ИС/ПО - каскадная, инкрементная, итеративная, спиральная;
- подходы к разработке ИС/ПО: предиктивный подход, адаптивный подход, гибридный подход

### Подраздел 4.2.
Календарный план-график работ по проекту на разработку ИС/ПО
Календарный план-график работ по проекту на разработку ИС/ПО может быть представлен в виде таблицы с указанием состава и трудоемкости выполнения работ на всех стадиях проекта, а также исполнителей и ответственных за выполнение каждого вида работ. Приветствуется дополнительное графическое отображение план-графика в форме диаграммы Ганта. Для построения диаграммы Ганта можно использовать шаблоны Excel.

### Подраздел 4.3.
Анализ рисков на разработку и внедрение ИС/ПО и меры по их устранению.

Описание возможных рисков реализации проекта, обусловленных как внутренними, так и внешними причинами. Описание мероприятий по устранению рисков.


## Раздел 5.
Анализ качественных и количественных факторов воздействия проекта на бизнес-архитектуру организации (экономический, эргономический, социальный и др. эффекты)

Качественные и количественные показатели проекта (KPI) (пользовательские требования к быстродействию, надежности, эргономике системы, информационной безопасности и др.).


## Заключение

- Констатация выполнения задач и достижения цели проекта с указанием полученных результатов.
- Перечисление проблем, не решенных в рамках проекта, на которые автор предполагает направить дальнейшую деятельность.


## Список используемой литературы

- Список законодательных и нормативных документов
- Список литературных и журнальных источников в алфавитном порядке
- Список интернет-источников


## Состав исполнителей


## Приложения
Распечатки моделей, схем, таблиц и др.
