---
title: Примерные темы итоговых проектов
author:
  - Голкина Г.Е.
date: 2025-09-01
date-modified: last-modified

format:
  html: default
---


## Примечание
Тему можно выбрать из списка или предложить свою.

В названии темы обязательно должны присутствовать слова:

1. «разработка системы», или «автоматизация процесса», или «разработка программного модуля», или «разработка сайта», «разработка программного модуля (название чат-бота)» (если разрабатывается чат-бот);
2. название процесса, который автоматизируется;
3. название организации, процесс которой автоматизируется (название организации может быть гипотетическое, например, банк, юридическая компания, юридический отдел, ВУЗ, нотариальная контора, районный суд и др.)


## Примерные темы итоговых проектов

1. Разработка системы электронного документооборота в юридической компании ________ (название).
2. Автоматизация процесса подготовки правовых заключений в ________ (название организации).
3. Разработка программного модуля «название чат-бота» юридической поддержки клиентов компании ________ (название).
4. Автоматизация процесса мониторинга законодательства в _________ (название организации).
5. Автоматизация процесса выдачи разрешительной документации (например, справка на ношение оружия, получение российского паспорта и др.) в ____________ (название организации).
6. Автоматизация процесса мониторинга и проверки контрагентов на благонадежность в юридической компании ___________ (название).
7. Автоматизация процесса мониторинга и анализа конкурентов (в т.ч., в рамках участия в госзакупках) в ___________ (название организации).
8. Автоматизация процесса ведения дел в районном суде.
9. Автоматизация процесса делопроизводства в суде общей юрисдикции.
10. Разработка программного модуля анализа судебной практики для ____________ (название организации).
11.  Разработка программного модуля управления юридическими рисками в ___________ (название организации).
12. Автоматизация контроля учета рабочего времени сотрудников в _____________ (название организации).
13.  Автоматизация процесса договорной работы в ___________ (название организации).
14. Автоматизация судебной работы секретаря судебного заседания в суде общей юрисдикции.
15.   Автоматизация деятельности адвокатской конторы.
16.  Автоматизация процесса оказания юридической поддержки клиентам адвокатской конторы.
17.  Разработка программного модуля заключения договоров в __________ (название организации) с применением технологии искусственного интеллекта.
18.  Автоматизация процесса регистрации права собственности на объекты недвижимости в ______________ (название организации).
19.  Разработка программного модуля «Конструктор договоров» с использованием сервиса Manybot.
20.   Разработка программного модуля «название» определения подсудности по спорам гражданско-правового характера.
21.  Разработка программного модуля «название» деятельности приемной комиссии ВУЗа.
22.  Автоматизация кадрового документооборота в «название организации» с использованием шаблонов документов.
23.  Разработка программного модуля «Юрист-бот» юридической поддержки клиентов в «название организации».
24.  Разработка программного модуля «Юридическая клиника» on-line консультирования граждан в ВУЗе.
25.  Разработка программного модуля «Выявление перспективных технологических направлений» интеллектуальной системы поддержки принятия решений в ВУЗе.
26.  Автоматизация процесса поиска судебных актов судов общей юрисдикции в «название организации».
