---
title: "{{< var titles.annotation.long >}}"
#author:
date: 2025-09-01
date-modified: last-modified

format:
  html: default
---


## Цель реализации программы дисциплины:
- получение новых компетенций в области управления проектами в ИT-сфере, системного представления о современной методологии управления ИT-проектами, комплексного подхода к процессам проектного управления на основе нормативного, методического и технологического обеспечения.


## Планируемые результаты обучения:
По итогам освоения дисциплины (модуля) обучающийся приобретает способности:
- разрабатывает концепцию проекта в рамках обозначенной проблемы: формулирует цель, задачи, обосновывает актуальность, значимость, ожидаемые результаты и возможные сферы их применения;
- планирует необходимые ресурсы, в том числе с учетом их заменимости;
- осуществляет мониторинг хода реализации проекта, корректирует отклонения, вносит дополнительные изменения в план реализации проекта, уточняет зоны ответственности участников проекта;
- планирует командную работу, распределяет поручения и делегирует полномочия членам команды.


## Оценка качества освоения дисциплины
Оценка качества освоения программы по дисциплине &laquo;Анализ и моделирование бизнес-процессов организации. Управление IТ-проектами&raquo; подразумевает три формы: текущий контроль, рубежный контроль и промежуточный контроль успеваемости.

**Текущий контроль** заключается в проверке домашних заданий, выполняемых слушателями к каждому практическому занятию. В рамках практических занятий по анализу бизнес-процессов планируется составление описания, представленного в виде блок-схем, одного юридического бизнес-процесса отдельно взятой компании. В рамках практических занятий по управлению IТ-проектами планируется составление описания работы над отдельным IТ-проектом в сфере автоматизации юридических процессов.

**Рубежный контроль** проводится в течение семестра в форме письменного теста или электронного тестирования. Промежуточный контроль успеваемости по дисциплине проводится на зачете.

Для успешной сдачи зачета слушателю необходимо ответить на вопросы билета.
