---
title: Зачет
#author:
date: 2024-09-01
date-modified: last-modified

format:
  html: default
---


## Вопросы для подготовки к зачету

1. Основные понятий проектного менеджмента, «проект», «управление проектом». Сравнение понятий «проект», «программа», «портфель проектов».
2. Общая характеристика проекта как объекта управления.
3. Субъекты управления проектом. Внешние и внутренние участники управления проектом. Отношения между понятиями управления проектами.
4. Система стандартов по управлению IИ-проектами, программами и портфелями проектов.
5. Цели, задачи и принципы внедрения управления проектами в ИT-cфере.
6. Перечислите основные ограничения ИТ-проекта.
7. Перечислите виды ресурсов ИТ – проекта.
8. Менеджер проекта: компетенции и задачи при управлении заинтересованными сторонами.
9. Организационная структура при проектном управлении.
10. Команда проекта и команда управления проектом.
11. Приведите определения жизненного цикла системы, проекта, программных средств.
12. Перечислите и охарактеризуйте процессы реализации ИТ- проекта.
13. Соотнесите области действия и порядок использования стандартов ИСО/МЭК 15288 и ИСО/МЭК 12207 для управления ИТ-проектами.
14. Планирование и управление проектом.
15. Типы задач проекта и типы связей между ними.
16. Планирование и управление ресурсами проекта.
17. Виды представления информации о проекте. Виды отчетов проекта.
18. Назначение диаграммы Ганта.
