---
title: "{{< var titles.annotation.long >}}"
#author:
date: 2024-09-01
date-modified: last-modified
---


## Цель реализации программы дисциплины:

- формирование у обучающихся представлений о современном состоянии и развитии рынка Legaltech для комплексного понимания вариантов оптимизации и автоматизации юридической работы.


## Планируемые результаты обучения:
По итогам освоения дисциплины (модуля) обучающийся приобретает способности:

- анализировать рынок программного обеспечения в сфере автоматизации юридических процессов;
- понимать новизну предлагаемых и/или внедряемых решений;
- оценивать эффективность создания нового ПО в сфере автоматизации юридических процессов;
- оценивать, подходит ли имеющееся на рынке ПО для задач, стоящих перед специалистом по автоматизации;
- предлагать внедрение и/или совершенствование ПО для автоматизации юридических процессов.


## Оценка качества освоения дисциплины
Оценка качества освоения программы по дисциплине &laquo;Автоматизация юридической работы (Legaltech)&raquo; подразумевает одну форму: промежуточный контроль успеваемости.

**Промежуточный контроль** успеваемости по дисциплине проводится на зачете.

Для успешной сдачи зачета слушателю необходимо подготовить краткую устную презентацию, отражающую конкретный юридический процесс и программные средства его автоматизации.
