project:
  type: website
  output-dir: ../build
  resources:
    - /_redirects


metadata-files:
  - algorithmics/_sidebar.yml
  - business-process-modeling/_sidebar.yml
  - it-project-management/_sidebar.yml
  - legaltech/_sidebar.yml
  - software-development-methodology/_sidebar.yml
  - traineeship/_sidebar.yml
  - project/_sidebar.yml
  - attestation/_sidebar.yml
  - bibliography/_sidebar.yml


website:
  site-url: https://msal.tech/
  favicon: _static/images/favicon.png

  announcement:
    icon: info-circle
    dismissable: true
    content: "Контент находится в разработке"
    type: primary
    position: above-navbar

  title: "Автоматизация юридических процессов"
  image: _static/images/logo.svg
  description: "Каталог учебных материалов по программе профессиональной переподготовки"
  open-graph:
    locale: ru_RU
  page-navigation: true
  bread-crumbs: true
  reader-mode: true

  # GitHub
  repo-url: https://github.com/msal-tech/msal-tech
  repo-subdir: src/
  issue-url: https://github.com/msal-tech/msal-tech/issues
  repo-link-target: _blank
  repo-actions: [edit, source, issue]


  # ---------------------------------------------------------------------------
  navbar:
    title: false
    #logo: "_static/images/logo.png"
    #logo-alt: "LegalTech"
    collapse-below: lg

    left:
      - text: "Главная"
        href: index.qmd
      - text: "О программе"
        href: annotation.qmd
      - text: "Учебные модули"
        icon: briefcase
        menu:
          - text: "Алгоритмика"
            icon: diagram-2
            href: algorithmics/index.qmd
            #
          - text: "Анализ и моделирование бизнес-процессов"
            icon: file-bar-graph
            href: business-process-modeling/index.qmd
            #
          - text: "Управление ИТ-проектами"
            icon: dpad
            href: it-project-management/index.qmd
            #
          - text: "Методологии разработки программного обеспечения"
            icon: file-code
            href: software-development-methodology/index.qmd
            #
          - text: "Автоматизация юридической работы (Legaltech)"
            icon: file-earmark-richtext
            href: legaltech/index.qmd
      - text: "Стажировка"
        href: traineeship/index.qmd
      - text: "Проект"
        href: project/index.qmd
      - text: "Аттестация"
        href: attestation/index.qmd
      - text: "Тестирование"
        href: assessment.qmd
      - text: "Литература"
        icon: book
        menu:
          - bibliography/basic.qmd
          - bibliography/additional.qmd
          - bibliography/electronic.qmd
    right:
      - about.qmd
      - authors.qmd
    search: true


  # ---------------------------------------------------------------------------
  sidebar:

    - style: "floating" # "docked" #
      collapse-level: 1
      align: left
      search: true
      pinned: true
      contents:
        - text: "О программе"
          href: annotation.qmd
        #- text: "---"
        - section: "Учебные модули"
          icon: briefcase
          # href: subjects.qmd
          contents:
            - text: "Алгоритмика"
              icon: diagram-2
              href: algorithmics/index.qmd
              #
            - text: "Анализ и моделирование бизнес-процессов"
              icon: file-bar-graph
              href: business-process-modeling/index.qmd
              #
            - text: "Управление ИТ-проектами"
              icon: dpad
              href: it-project-management/index.qmd
              #
            - text: "Методологии разработки программного обеспечения"
              icon: file-code
              href: software-development-methodology/index.qmd
              #
            - text: "Автоматизация юридической работы"
              icon: file-earmark-richtext
              href: legaltech/index.qmd

        - text: "Стажировка"
          href: traineeship/index.qmd
        - text: "Итоговый проект"
          href: project/index.qmd
        - text: "Итоговая аттестация"
          href: attestation/index.qmd

        - section: Литература
          icon: book
          contents:
            - bibliography/basic.qmd
            - bibliography/additional.qmd
            - bibliography/electronic.qmd

        - assessment.qmd


  # ---------------------------------------------------------------------------
  page-footer:
    left: |
      [Цифровая кафедра МГЮА](https://msal.ru/content/prioritet-2030/tsifrovaya-kafedra/){.external target="_blank"}
    center:
      - text: "Главная"
        href: about.qmd
      - text: "Учебные  модули"
        href: subjects.qmd
      - text: "Авторы"
        href: authors.qmd
    right:
      - href: https://github.com/msal-tech/msal-tech
        icon: github
        target: _blank
        aria-label: "GitHub"

execute:

    echo: false

jupyter: python3


format:
  #---------------------------------------------
  html:
    lang: ru
    toc: true
    theme:
      light:
        - cosmo
        - theme.scss
    code-copy: true
    code-overflow: wrap
    css: ./_static/styles/html.css
    #include-after-body: js.html

    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

    link-external-newwindow: true
    link-external-icon: true
    link-external-filter: ^(?:http:|https:)\/\/msal\.tech

  #----------------------------------------------
  pdf:
    lang: ru
    toc: true
    number-sections: true
    colorlinks: true
    keep-tex: false
    mainfont: "Times New Roman"
    monofont: "Times New Roman"
    sansfont: "Open Sans"
    mathfont: "Times New Roman"
    #template: template.tex

  revealjs:
    lang: ru
    slide-level: 4
    smaller: true
    center-title-slide: false
    css: ./_static/styles/revealjs.css

  #-----------------------------------------------
  # docx:
  #   toc: true
  #   toc-depth: 2
  #   section-numbers: true
  #   hightlight-style: github
  #   #reference-doc: template.docx

