---
title: О программе профессиональной подготовки
page-navigation: false
#author:
date: 2024-09-01
date-modified: last-modified

format:
  html: default
---


## Цели реализации программы

Дополнительная профессиональная программа профессиональной переподготовки ИТ-профиля (далее – Программа) предназначена для
обучающихся по специальностям и направлениям подготовки, не отнесенным к ИТ-сфере.

**Целью образовательной программы** является получение актуальной для отрасли &laquo;Социальная сфера&raquo; дополнительной ИТ–квалификации &laquo;менеджер по информационным технологиям&raquo;.

В рамках программы запланировано формирование дополнительных цифровых компетенций в области создания алгоритмов и программ, пригодных для практического применения, в том числе
компетенций, необходимых для работы в качестве одного из участников команды разработки программного обеспечения в сфере автоматизации
юридических процессов.
Программа предназначена для тех, кто стремится повысить свои профессиональные компетенции и получить дополнительную квалификацию, позволяющую сочетать свои специальные знания, полученные в результате освоения основной образовательной программы, и знания и навыки в сфере информационных технологий.


## Задачи программы

- повышение профессиональных навыков в области информационных технологий;
- выработка навыков совместной работы со специалистами в сфере информационных технологий по созданию программного обеспечения;
- выработка практических навыков информационно-поисковой деятельности, направленных на совершенствование профессиональных умений в области информационных технологий;
- практическое применение принципов и основ алгоритмизации;
- приобретение слушателями навыков использования результатов моделирования и анализа бизнес-процессов для принятия стратегических и оперативных управленческих решений.

Программа предназначена для тех, кто стремится повысить свою профессиональную компетенцию и получить дополнительную квалификацию, позволяющую сочетать свои специальные знания, полученные в результате освоения основной образовательной программы, и знания и навыки в сфере информационных технологий.


## Актуальность и уникальность программы

Изменения в обществе связанные с развитием информационных технологий приводят к резкому увеличению потребности в менеджерах по управлению сервисами ИT. Менеджер по информационным технологиям сейчас и в ближайшем будущем имеет большие возможности для трудоустройства и карьерного роста в этой области.


## Формы обучения и материалы

Программа сочетает теорию и практику, а материалы структурированы для максимально эффективного погружения:

- **Лекции** --- видеозаписи, презентации и конспекты по основам автоматизации юридической деятельности.
- **Семинарские занятия** --- интерактивные кейсы, шаблоны решений и рекомендации по работе с Legaltech-инструментами.
- **Дистанционная практика/стажировка** --- гайды, чек-листы и примеры проектов для отработки навыков в реальных условиях.
- **Защита проекта** --- методические указания, образцы документов и критерии оценки финальной работы.
- **Зачеты и экзамены** --- тесты, практические задания и примеры вопросов для самоподготовки.


## Объем и сроки реализации программы
- **Объем:** 398 академических часов.
- **Продолжительность:** 9 месяцев.
- **Формат:** очный и дистанционный.


## Требования к поступающим

К обучению по Программе допускаются лица, обучающиеся по очной, очно-заочной форме за счет бюджетных средств или по договорам об оказании платных образовательных услуг, освоившие часть основной профессиональной образовательной программы высшего образования бакалавриата – в объеме не менее 60 зачетных единиц (бакалавры 2-го курса), освоившие часть основной профессиональной образовательной программы высшего образования специалитета - в объеме не менее 120 зачетных единиц (специалисты 2-го курса), а также обучающиеся по программам магистратуры, которые не относятся к ИТ-профилю, по специальностям и направлениям подготовки в отрасли экономики &laqou;Социальная сфера&raqou;.

К освоению программы допускаются обучающиеся очной, очно-заочной форм обучения.
По результатам прохождения базового курса &laqou;Введение в автоматизацию юридических процессов&raqou; слушатели распределяются в следующие группы:

- целевая группа 1 – базовая подготовка;
- целевая группа 2 – продвинутая подготовка.

Подать заявку на обучение можно на странице [&laquo;цифровой кафедры&raquo;](https://msal.ru/content/prioritet-2030/tsifrovaya-kafedra/?clear_cache=Y#SUCCESS_24) Университета имени О.Е. Кутафина (МГЮА).

## Квалификационная характеристика выпускника.

Выпускникам Программы присваивается дополнительная ИТ-квалификация в области управления внедрением, предоставлением, использованием и развитием цифровых и информационных технологий в юридической деятельности (отрасль &laqou;Социальная сфера&raqou;, согласно &laquo;Требованиям к  содержанию и оформлению дополнительных профессиональных программ (программ профессиональной переподготовки) и ИТ-модулей в рамках предусматривающих получение нескольких квалификаций основных программ высшего образования, реализуемых на &laqou;цифровых кафедрах&raqou; образовательными организациями высшего образования, участвующих в программе стратегического академического лидерства &laqou;Приоритет-2030&raqou;)&raquo.

Выпускник Программы будет готов к выполнению трудовой деятельности, связанной с использованием вычислительной техники и информационных технологий (код ОКВЭД – 62.09, согласно Профессионального стандарта &laqou;Менеджер по информационным технологиям&raqou;, утв. Приказом Министерства труда и социальной защиты РФ от 30 августа 2021 г. N 588н &laquo;Об утверждении профессионального стандарта &laqou;Менеджер по информационным технологиям&raqou;) в качестве менеджера по информационным технологиям.

Квалификационный уровень по национальной рамке квалификаций: 6.

### Профессиональные задачи

Обучающийся, освоивший дополнительную профессиональную программу, должен быть готов решать следующие профессиональные задачи:

- **проектная деятельность:**
  - проведение обследования прикладной области в соответствии с профилем подготовки: сбор детальной информации для формализации требований пользователей заказчика, интервьюирование ключевых сотрудников заказчика;
  - формирование требований к информатизации и автоматизации прикладных процессов, формализация предметной области проекта;
  - моделирование прикладных и информационных процессов, описание реализации информационного обеспечения прикладных задач;
  - составление технического задания на разработку информационной системы; проектирование информационных систем в соответствии со спецификой профиля подготовки по видам обеспечения (программное, информационное, организационное, техническое);
  - участие в проведении переговоров с заказчиком и выявление его информационных потребностей;
- **организационно-управленческая деятельность:**
  - участие в проведении переговоров с заказчиком и презентация проектов;
  - координация работ по созданию, адаптации и сопровождению информационной системы;
  - участие в организации работ по управлению проектом информационных систем;
  - участие в управлении бизнес-процессами, основанном на их анализе и моделировании;
  - взаимодействие с заказчиком в процессе реализации проекта;
- **аналитическая деятельность:**
  - анализ и выбор проектных решений по созданию и модификации информационных систем;
  - оценка рисков проектных решений, эффективности информационной системы.


## Планируемые результаты освоения программы
Выпускник, освоивший образовательную программу &laquo;Автоматизация юридических процессов&raquo;, должен обладать компетенциями, соответствующими виду (видам) профессиональной деятельности, на который (которые) ориентирована программа:

### Общие профессиональные компетенции:
- способность использовать нормативно-правовые документы, международные и отечественные стандарты в области информационных систем и технологий;
- способность анализировать социально-экономические задачи и процессы с
- применение методов системного анализа;
- способность разрабатывать алгоритмы;
- способность проводить анализ и моделирование бизнес-процессов.

### Профессиональные компетенции:
- **Проектная деятельность**:
  - способность проводить обследование организаций, выявлять информационные потребности пользователей, формировать требования к информационной системе;
  - способность участвовать в разработке, внедрении и адаптации прикладного программное обеспечение;
  - способность проектировать ИС в сфере автоматизации юридической работы;
  - способность формулировать обоснование проектных решений;
  - способность собирать информацию для формализации требований пользователей заказчика;
  - способность проводить описание прикладных процессов и информационного обеспечения решения прикладных задач;
  - способность составлять техническую документацию проектов автоматизации и информатизации прикладных процессов;
  - организационно-управленческая деятельность:
  - способность принимать участие в управлении проектами создания информационных систем на стадиях жизненного цикла;
  - способность принимать участие в реализации профессиональных коммуникаций в рамках проектных групп, обучать пользователей информационных систем.
- **Аналитическая деятельность**:
  - способность осуществлять и обосновывать выбор проектных решений по видам обеспечения информационных систем;
  - способность проводить оценку рисков при создании информационных систем;
  - способностью анализировать рынок программно-технических средств, информационных продуктов и услуг для создания и модификации информационных систем.


## Дисциплины (модули)
Изучайте актуальные направления, которые помогут стать экспертом в цифровой юриспруденции:

1. [**Алгоритмика:**](algorithmics/ "Алгоритмика")
   Основы программирования, автоматизация рутинных задач и работа с данными.
2. [**Анализ и моделирование бизнес-процессов:**](business-process-modeling/ "Анализ и моделирование бизнес-процессов")
   Инструменты оптимизации юридических workflows: BPMN, схемы процессов, кейсы.
3. [**Управление ИТ-проектами:**](it-project-management/ "Управление ИТ-проектами")
   Agile, Scrum, RACI-матрицы --- управляйте цифровыми решениями уверенно.
4. [**Методологии разработки ПО:**](software-development-methodology/ "Методологии разработки ПО")
   От проектирования до внедрения: жизненный цикл ПО и интеграция в юридическую практику.
5. [**Автоматизация юридической работы (Legaltech):**](legaltech/ "Автоматизация юридической работы (Legaltech)")
   AI, блокчейн, электронный документооборот --- технологии, которые меняют профессию.


## Для вас, если вы:
- Студент **МГЮА имени О.Е. Кутафина**, стремящийся стать востребованным специалистом на стыке права и IT.
- Хотите систематизировать знания, получить практические навыки и создать проект для портфолио.


## Почему стоит использовать материалы сайта?
- **Структурированная подача** --- все лекции, задания и дополнительные ресурсы в одном месте.
- **Поддержка на каждом этапе** --- гайды, шаблоны и примеры упростят подготовку к экзаменам и защите проекта.
- **Доступ к экспертизе** --- материалы подготовлены практикующими юристами и IT-специалистами.
- **Сертификат &laquo;Иннополиса&raquo;** --- дополнительные материалы помогут успешно пройти ассесмент и подтвердить уровень навыков.


**Ваше обучение --- это инвестиция в будущее.**
Используйте материалы, задавайте вопросы в обсуждениях и достигайте целей! Каждый модуль --- шаг к профессии юриста нового поколения.

**Освойте Legaltech, станьте экспертом в автоматизации права и откройте новые карьерные возможности!**
