---
title: Авторы
page-navigation: false
#author:
date: 2025-09-01
date-modified: last-modified

format:
  html: default
---


Программа составлена при участии и экспертизе компаний КонсультантПлюс, Гарант и Botman.one.


## Авторы программы

- **Минбалеев А.В.** &mdash;  д.ю.н., заведующий кафедрой информационного права и цифровых технологий ФГАОУ ВО &laquo;Московский государственный юридический университет имени О.Е. Кутафина (МГЮА)&raquo;.
- **Наумов В.Б.** &mdash;  д.ю.н., профессор кафедры информационного права и цифровых технологий, управляющий партнер санкт-петербургского офиса DENTONS, соруководитель европейской практики в области регулирования Интернета и технологий.
- **Мартынова Т.Л.** &mdash;  к.т.н., доцент кафедры информационного права и цифровых технологий ФГАОУ ВО &laquo;Московский государственный юридический университет имени О.Е. Кутафина (МГЮА)&raquo;.
- **Соломатин Е.Б.** &mdash;  к.ф.-м.н., эксперт РАНХиГС, руководитель программы МВА Телеком бизнес-школы МИРБИС, директор по развитию компании &laquo;Мегапьютер Интеллидженс&raquo;;
- **Большаков Д.В.** &mdash;  создатель low-code системы Botman.one.
- **Авакян Е.Г.** &mdash;  преподаватель кафедры интеллектуальных прав, советник адвокатского бюро &laquo;Егоров, Пугинский, Афанасьев и партнеры&raquo;, исполнительный директор НК &laquo;Содействие развитию корпоративного законодательства&raquo;, действительный государственный советник юстиции 2 класса.
- **Соловьева Е.В.** &mdash;  к.п.н., руководитель проекта &laquo;Цифровая кафедра&raquo; Центра управления изменениями ФГАОУ ВО &laquo;Московский государственный юридический университет имени О.Е. Кутафина (МГЮА)&raquo;.


## Авторы учебных материалов


- **Агеев Михаил Евгеньевич** &mdash; преподаватель кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Андреев Михаил Александрович** &mdash; преподаватель кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Баринов Игорь Игнатьевич** &mdash; преподаватель кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Бречалов Дмитрий Альбионович** &mdash; преподаватель кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Брозгунова Надежда Петровна** &mdash;  к.э.н., доцент кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Внукова Тамара Васильевна** &mdash; преподаватель кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Голкина Галина Евгеньевна** &mdash;  к.э.н., доцент кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Горбунов Валерий Николаевич** &mdash; преподаватель кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Гранкина Анна Всеволодовна** &mdash; преподаватель кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Гранухина Анастасия Николаевна** &mdash; преподаватель кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Грищенко Галина Андреевна** &mdash; к.ю.н., доцент кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Дергач Галина Анатольевна** &mdash; преподаватель кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Караванов Богдан Евгеньевич** &mdash; преподаватель кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Каширина Наталия Владимировна** &mdash; преподаватель кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Комин Алексей Владимирович** &mdash; преподаватель кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Красников Александр Сергеевич** &mdash;  к.ф.-м.н., доцент кафедры &laquo;Информационная безопасность&raquo; Московского политехнического университета, доцент кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Красноперов Илья Сергеевич** &mdash; преподаватель кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Левченко Елена Викторовна** &mdash; преподаватель кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Макаров Максим Игоревич** &mdash; преподаватель кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Михайлов Александр Геннадьевич** &mdash;  к.т.н., MBA, MBA по стратегическому управлению, Генеральный директор компании &laquo;Консалтинг по управлению ИТ&raquo;, преподаватель по ИТ-стратегиям и цифровой трансформации бизнеса (в бизнес-школах МИРБИС, РАНХиГС, ГУУ и др.), старший преподаватель кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Никишин Владимир Дмитриевич** &mdash; к.ю.н., доцент кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Плотников Андрей Георгиевич** &mdash; к.ф.-м.н., доцент кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Портнов Дмитрий Борисович** преподаватель кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Фролова Александра Леонидовна** преподаватель кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Шельменков Валентин Николаевич** преподаватель кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
- **Юдин Вадим Викторович** преподаватель кафедры информационного права и цифровых технологий Университета имени О.Е. Кутафина (МГЮА)
