---
title: Экзамен
#author:
date: 2024-09-01
date-modified: last-modified

format:
  html: default
---


## Вопросы для подготовки к экзамену

1. Понятие алгоритма.
2. Свойства алгоритмов.
3. Способы записи алгоритмов.
4. Понятие и назначение блок-схемы. Основные элементы блок-схемы.
5. Непосредственное и программное управление исполнителем.
6. Линейные программы.
7. Алгоритмические конструкции, связанные с проверкой условий.
8. Циклические алгоритмические конструкции.
9. Виды циклов
10. Понятие простой величины.
11. Типы величин: целые, вещественные, символьные, строковые,логические.
12. Переменные и константы.
13. Понятия массива данных
14. Этапы разработки алгоритма.
15. Сложные алгоритмы.
16. Вложенные алгоритмы.
17. Итерационные алгоритмы
18. Рекурсия.
19. Понятие сортировки
20. Сортировка пузырьком (Bubble Sort)
21. Шейкерная сортировка
22. Сортировка расческой
23. Сортировка вставками (Insertion Sort)
24. Сортировка выбором (Selection Sort).
25. Сортировка слиянием
26. Быстрая сортировка
27. Пирамидальная сортировка (Сортировка кучей)
28. Кибернетическая система.
29. Структура кибернетической системы.
30. Прямая и обратная связь в кибернетической системе.
31. Алгоритм управления.
32. Кибернетическая модель управления.
