---
title: "{{< var titles.annotation.long >}}"
#author:
date: 2024-09-01
date-modified: last-modified

format:
  html: default
---


## Цель реализации программы дисциплины:
- формирование у обучающихся представления об организации процесса разработки ПО. По итогу обучающиеся должны понимать, какие влияние оказывает принятая методология разработки на процессы проектирования и разработки программного обеспечения, а также на управление командой разработки.


## Планируемые результаты обучения:
По итогам освоения дисциплины (модуля) обучающийся приобретает способности:

- описывает особенности жизненного цикла разработки ПО;
- знает и понимает, что такое методологии разработки ПО;
- понимает, как учитывать различные факторы проекта (внутренние и внешние) при выборе методологии разработки ПО;
- понимает, какие факторы могут иметь влияние на выбор методологии разработки ПО;
- знает и понимает базовые понятия области анализа требований;
- выявляет и анализирует требования, управляет ими;
- управляет изменениями требований;
- умеет формировать техническое задание;
- знает базовые архитектурные паттерны клиентских и серверных приложений;
- знает и понимает основные разделы технического задания;
- знает и понимает различные модели разработки и их особенности.


## Оценка качества освоения дисциплины
Оценка качества освоения программы по дисциплине &laquo;Методология разработки программного обеспечения&raquo; подразумевает три формы: текущий контроль, рубежный контроль и промежуточный контроль успеваемости.

**Текущий контроль** заключается в проверке домашних заданий, выполняемых слушателями к каждому практическому занятию.

**Рубежный контроль** проводится в течение семестра в форме письменного теста или электронного тестирования.

**Промежуточный контроль** успеваемости по дисциплине проводится на зачете.
Для успешной сдачи зачета слушателю необходимо ответить на вопросы билета.
