---
title: Зачет
#author:
date: 2025-09-01
date-modified: last-modified

format:
  html: default
---


## Вопросы для подготовки к зачету

1.Понятие программного обеспечения.
2. Жизненный цикл программного обеспечения.
3. Классические методологии разработки программных средств.
4. Каскадные и итеративные технологии.
5. Критичность и масштабность программных проектов.
6. Технологии быстрой разработки программного обеспечения.
7. Технология экстремального программирования.
8. SCRUM технология.
9. Преимущества и недостатки технологий быстрой разработки программного обеспечения.
10. Организация коллективной работы над проектом при использовании технологий быстрой разработки.
11. Объектно-ориентированное проектирование программной системы.
12. Построение объектно-ориентированной архитектуры системы.
13. Методы объектно-ориентированного анализа для выявления классов и объектов.
14. CASE - средства объектно-ориентированного проектирования.
15. Стандарты разработки ПО и CASE-технологии.
16. Средства информационной поддержки программных проектов и изделий (CALS) технологий.
17. Средства управления проектами. Применение данных средств при разработке и сопровождении программных продуктов.
18. Виды и типы языков программирования.
19. Виды и типы программ.
20. Цели и задачи создания программного обеспечения.
21. Требования к программной системе.
22. Работа с заказчиком. Обследование системы, общение с заказчиком, планирование разработки, составление технического задания.
23. Детальный анализ предметной области, принятие окончательного решения о необходимости создания информационной системы, проектирование общей архитектуры системы, выбор метода проектирования.
24. Понятие «функциональных требований» и «технического задания».
25. Требования к написанию «функциональных требований» и «технического задания».
26. Оценка качества программного обеспечения. Методики оценки качества ПО.
27. Процессный подход к оценке качества ПО.
28. Внедрение и сопровождение программных продуктов.
29. Планирование процесса внедрения программного продукта.
30. Основные задачи решаемые на этапе внедрения. Процесс устранения ошибок на этапе внедрения.
31. Техническая поддержка пользователей на этапе сопровождения.
32. Роль юристов в процессе написания «функциональных требований» и «технического задания».
